name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        os-environment: [ubuntu-20.04]
    runs-on: ${{ matrix.os-environment }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: run pylint
      run: |
        cd ./src/devana
        pylint --recursive=y  ./src/devana