name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, 3.10]
        os-environment: [ubuntu-20.04, windows-2019, macos-10.15]
    runs-on: ${{ matrix.os-environment }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: run tets
      run: |
        python -m tox -e py
  build_doc:
    needs: tests 
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.8]
        os-environment: [ubuntu-20.04]
    runs-on: ${{ matrix.os-environment }}
    steps:
    - name: Full checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Build package
      run: |
        python -m build
    - name: Build documentation
      shell: bash
      run: |
        python build_local.py
        rm -d -r docs
        python build_doc.py